import { Injectable } from '@nestjs/common';
import { Content, DynamicContent, PageOrientation } from 'pdfmake/interfaces';
import { PdfConfigService, PDF_COLORS, FONT_SIZES } from './pdf-config.service';

@Injectable()
export class PdfHeaderFooterService {
  constructor(private config: PdfConfigService) {}

  buildHeader(
    reportName: string,
    dateRange?: { startDate?: string; endDate?: string },
  ): DynamicContent {
    return (
      currentPage: number,
      pageCount: number,
      pageSize: { width: number; height: number; orientation: PageOrientation },
    ) => {
      const headerContent: any[] = [];
      const pageWidth = pageSize.width;
      const margin = 40;

      const logo = this.config.getLogo();

      const periodText =
        dateRange?.startDate || dateRange?.endDate
          ? this.formatDateRange(dateRange)
          : 'Period: All Time';

      const headerTable: any = {
        table: {
          widths: [100, '*', 100],
          body: [
            [
              logo
                ? {
                    image: logo,
                    width: 40,
                    height: 40,
                    alignment: 'left',
                    fillColor: PDF_COLORS.white,
                  }
                : { text: '', alignment: 'left' },
              {
                stack: [
                  { text: reportName, style: 'title', alignment: 'center' },
                  {
                    text: periodText,
                    fontSize: FONT_SIZES.small,
                    color: PDF_COLORS.body,
                    alignment: 'center',
                    margin: [0, 2, 0, 0],
                  },
                ],
                alignment: 'center',
              },
              {
                text: new Date().toLocaleDateString('en-US', {
                  year: 'numeric',
                  month: 'short',
                  day: 'numeric',
                }),
                fontSize: FONT_SIZES.small,
                color: PDF_COLORS.body,
                alignment: 'right',
              },
            ],
          ],
        },
        layout: 'noBorders',
        margin: [margin, 10, margin, 0],
      };

      headerContent.push(headerTable);

      headerContent.push({
        canvas: [
          {
            type: 'line',
            x1: margin,
            y1: 0,
            x2: pageWidth - margin,
            y2: 0,
            lineWidth: 1,
            lineColor: PDF_COLORS.primary,
          },
        ],
        margin: [0, 4, 0, 0],
      });

      return headerContent as any;
    };
  }

  buildFooter(): DynamicContent {
    return (currentPage: number, pageCount: number) => {
      return [
        {
          canvas: [
            {
              type: 'line',
              x1: 0,
              y1: 0,
              x2: 515,
              y2: 0,
              lineWidth: 0.5,
              lineColor: PDF_COLORS.border,
            },
          ],
          margin: [40, 0, 40, 4],
        } as any,
        {
          columns: [
            {
              text: 'Generated by Lakshya LMS',
              fontSize: FONT_SIZES.small,
              color: PDF_COLORS.body,
              alignment: 'left',
            },
            {
              text: `Page ${currentPage} of ${pageCount}`,
              fontSize: FONT_SIZES.small,
              color: PDF_COLORS.body,
              alignment: 'right',
            },
          ],
          margin: [40, 0, 40, 10],
        } as any,
      ];
    };
  }

  buildInfoCard(
    title: string,
    items: { label: string; value: string }[],
  ): Content {
    const headerRow: any = {
      text: title,
      style: 'subsectionHeader',
      color: PDF_COLORS.white,
      fillColor: PDF_COLORS.primary,
      margin: [8, 6, 8, 6],
      colSpan: 2,
    };
    const dataRows = items.map((item) => [
      {
        text: `${item.label}:`,
        bold: true,
        color: PDF_COLORS.body,
        fontSize: FONT_SIZES.body,
        noWrap: false,
        margin: [8, 4, 4, 4],
      },
      {
        text: item.value || '-',
        color: PDF_COLORS.black,
        fontSize: FONT_SIZES.body,
        noWrap: false,
        margin: [4, 4, 8, 4],
      },
    ]);
    return {
      table: {
        widths: [120, '*'],
        body: [[headerRow, {}], ...dataRows],
      },
      layout: {
        hLineWidth: (i: number, node: any) =>
          i === 0 || i === 1 || i === node.table.body.length ? 0.5 : 0,
        vLineWidth: () => 0.5,
        hLineColor: () => PDF_COLORS.border,
        vLineColor: () => PDF_COLORS.border,
        paddingLeft: () => 0,
        paddingRight: () => 0,
        paddingTop: () => 0,
        paddingBottom: () => 0,
      },
      margin: [0, 0, 0, 8],
    } as any;
  }

  buildSummaryCard(summary: { label: string; value: string }[]): Content {
    const leftItems: { label: string; value: string }[] = [];
    const rightItems: { label: string; value: string }[] = [];

    summary.forEach((item, index) => {
      if (index % 2 === 0) {
        leftItems.push(item);
      } else {
        rightItems.push(item);
      }
    });

    const buildColumn = (items: { label: string; value: string }[]) => ({
      stack: items.map((item) => ({
        text: `${item.label}: ${item.value}`,
        fontSize: FONT_SIZES.body,
        margin: [0, 1, 0, 1],
      })),
    });

    return {
      columns: [
        { ...buildColumn(leftItems), width: '50%' },
        { ...buildColumn(rightItems), width: '50%' },
      ],
      margin: [0, 0, 0, 8],
    } as any;
  }

  private formatDateRange(dateRange?: {
    startDate?: string;
    endDate?: string;
  }): string {
    const fmt = (d?: string) =>
      d
        ? new Date(d).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
          })
        : null;

    if (dateRange?.startDate && dateRange?.endDate) {
      return `Period: ${fmt(dateRange.startDate)} — ${fmt(dateRange.endDate)}`;
    }
    if (dateRange?.startDate) {
      return `Period: From ${fmt(dateRange.startDate)}`;
    }
    if (dateRange?.endDate) {
      return `Period: Up to ${fmt(dateRange.endDate)}`;
    }
    return 'Period: All Time';
  }
}
